# Generated by Django 4.1.4 on 2023-07-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0002_question_like_count_question_pub_date_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='view_count',
        ),
    ]
