# Generated by Django 4.1.4 on 2023-07-30 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0004_rename_created_at_answer_pub_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='view_count',
        ),
    ]
